spring.application.name=ai-agent

# Base & Chat Configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=models/gemini-3.6-flash

# Embedding Configuration
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001